
name: git
version: 0.0.2
language: 
description: Clone code from repository
public: true
tags:
  - git
inputs:
  - name: FLOW_GIT_EVENT_TYPE
    editable: false
  - name: FLOW_GIT_HOST
    editable: false
  - name: FLOW_SECRET_PROJECT_PRIVATE_KEY
    editable: false
  - name: FLOW_GIT_BRANCH
    editable: false
  - name: FLOW_PROJECT_GIT_URL
    editable: false
  - name: FLOW_PROJECT_NAME
    editable: false
  - name: FLOW_GIT_CURRENT_BRANCH
    editable: false
  - name: FLOW_GIT_CURRENT_SSH_URL
    editable: false
  - name: FLOW_GIT_TARGET_BRANCH
    editable: false
  - name: FLOW_GIT_SPECIFIED_COMMIT
    editable: false
  - name: FLOW_GIT_TAG
    editable: false
  - name: FLOW_CACHE_REPO
  editable: false
outputs:
  - name: FLOW_GIT_BRANCH
  - name: FLOW_GIT_SPECIFIED_COMMIT
  - name: FLOW_PROJECT_GIT_URL
script_path: ./run.sh  
  
template: |  
  
  