
name: git
version: 0.0.2
language: 
description: 从 Git 仓库 clone
public: true
tags:
  - git
  
inputs:
  - name: FLOW_CACHE_REPO
    editable: true
    desc_cn: "缓存 git 仓库"
    desc_en: "Git repo cache"
    category: "switcher"
    default: 'FALSE'
    
outputs:
  - name: FLOW_GIT_BRANCH
  - name: FLOW_GIT_SPECIFIED_COMMIT
  - name: FLOW_PROJECT_GIT_URL
  
script_path: ./run.sh  
  
template: |  
  
  
